### PR TITLE
KSP2: fix KSValueParameter.isVal and isVar

### LINKED ISSUE #1192: Incorrect KSValueParameter#isVal/isVar() when inspecting precompiled class.
I'm running into an issue where `KSValueParameter#isVal()` and `KSValueParameter#isVar()` seem incorrect for a precompiled class like:

```kotlin
class MyClass(
    field: String,
    val valField: String,
    var varField: String,
)
```

In particular, I'm getting the following:

```
 fieldName | isPrecompiled | isVal() | isVar() 
-----------+---------------+---------+----------
  field    |     false     |  false  | false      // Correct
  valField |     false     |  true   | false      // Correct
  varField |     false     |  false  | true       // Correct
-----------+---------------+---------+----------
  field    |     true      |  true   | false      // Incorrect
  valField |     true      |  true   | false      // Correct
  varField |     true      |  true   | false      // Incorrect
```

Note that when `isPrecompiled=true` then `isVal()` always returns `true` and `isVar()` always returns `false`.

### PR DESCRIPTION
**Pull request by ting-yuan**
for symbols from libraries.

Fixes #1192 and #2348

### CODE REVIEW

File: kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt [hunk 1]
```diff
@@ -77,11 +81,26 @@ class KSValueParameterImpl private constructor(
...
 
+    private val KaValueParameterSymbol.primaryConstructorProperty: KaPropertySymbol? by lazy {
+        when (ktValueParameterSymbol.origin) {
+            // ktValueParameterSymbol.generatedPrimaryConstructorProperty is always null in libraries.
+            // TODO: fix in AA
+            KaSymbolOrigin.LIBRARY, KaSymbolOrigin.JAVA_LIBRARY -> analyze {
+                val cstr = ktValueParameterSymbol.containingDeclaration as? KaConstructorSymbol
+                val cls = cstr?.containingDeclaration as? KaClassSymbol
+                cls?.declaredMemberScope?.declarations?.filterIsInstance<KaPropertySymbol>()
+                    ?.firstOrNull { it.name == ktValueParameterSymbol.name }
```
Comment (jsjeon) [inline kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt:92]: In addition to `name` check, you can use `isFromPrimaryConstructor`: https://github.com/JetBrains/kotlin/blob/master/analysis/analysis-api/src/org/jetbrains/kotlin/analysis/api/symbols/KaVariableSymbol.kt#L245 ?

Comment (ting-yuan) [reply kotlin-analysis-api/src/main/kotlin/com/google/devtools/ksp/impl/symbol/kotlin/KSValueParameterImpl.kt:92]: Unfortunately `isFromPrimaryConstructor` is also PSI based and doesn't work on libraries.

But that reminds me of a case that this patch doesn't cover:
```
class MyClass(prop: Int = 1) {
    val prop: Int = 0
}
```

IMHO it is impossible to distinguish without adding metadata in the libraries.

Anyway, this patch covers most of the use cases and doesn't introduce new issues. If there are no other concerns, I'm going to merge it.
