### PR TITLE
Exclude generated libraries from deps

### LINKED ISSUE #1280: Incremental compilation fails with "Number of loaded files in snapshots differs"
We are building support for KSP in Micronaut (a popular Java/Kotlin framework). The initial implementation is done but it fails with KSP incremental compilation enabled with an error "Number of loaded files in snapshots differs" on the second compile:

```
./gradlew test
> Task :kspKotlin FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':kspKotlin'.
> Number of loaded files in snapshots differs. Reported changed files: []
```

To reproduce download this example project and run `./gradlew cTK` twice.

[ksp-test2.zip](https://github.com/google/ksp/files/10480874/ksp-test2.zip)

### PR DESCRIPTION
**Pull request by ting-yuan**
Fixes #1280

### CODE REVIEW

File: gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt [hunk 1]
```diff
@@ -514,6 +514,7 @@ class KspGradleSubplugin @Inject internal constructor(private val registry: Tool
                         kspTask.compilerOptions.freeCompilerArgs.value(
                             kspOptions + kotlinCompileTask.compilerOptions.freeCompilerArgs.get()
                         )
+                        kspTask.compilerOptions.useK2.value(false)
```
Comment (neetopia) [inline gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt:517]: is this related to this fix?

**Review by neetopia — APPROVED** [review]

File: gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt (hunk 1 above)
Comment (ting-yuan) [reply gradle-plugin/src/main/kotlin/com/google/devtools/ksp/gradle/KspSubplugin.kt:517]: Not specific to #1280, but a fix that is small enough to come with other commits.
