### PR TITLE
Fix subtype checking for Java types.

### LINKED ISSUE #890: `isAssignableFrom` behaves incorrectly with Java-specific types (from `Resolver.getJavaClassByName`)
Suppose we do the following:
```kotlin
val javaCollection = resolver.getJavaClassByName("kotlin.collections.Collection")  // maps to `java.util.Collection`
val javaSet = resolver.getJavaClassByName("kotlin.collections.Set")  // maps to `java.util.Set`
javaCollection.isAssignableFrom(javaSet)  // Expected: true, actual: false
```
As far as my investigations went, Kotlin compiler basically walks type hierarchy. And the superinterface for `java.util.Set` is `kotlin.collections.Collection` for some reason, not `java.util.Collection`. Thus, `java.util.Collection` is never encountered and check ends with negative result.

### PR DESCRIPTION
**Pull request by neetopia**
Compiler subtype checking does not convert Java types to Kotlin types, while getting super types from a java type does the conversion, therefore resulting in subtype checking for Java types to fail.
Check if candidate super type is a Java type, convert to Kotlin type for subtype checking.
Potentially needs an ultimate fix in compiler for subtype checking.

fixes #890

### CODE REVIEW

File: compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt [hunk 1]
```diff
@@ -77,7 +81,18 @@ class KSTypeImpl private constructor(
...
-        return subType.isSubtypeOf(kotlinType)
+        val declarationDescriptor = kotlinType.constructor.declarationDescriptor
+        // Compiler subtype checking does not convert Java types to Kotlin types, while getting super types
+        // from a java type does the conversion, therefore resulting in subtype checking for Java types to fail.
+        // Check if candidate super type is a Java type, convert to Kotlin type for subtype checking.
+        val thisType = if (declarationDescriptor is JavaClassDescriptor) {
+            JavaToKotlinClassMapper
+                .mapJavaToKotlin(declarationDescriptor.fqNameSafe, ResolverImpl.instance.module.builtIns)
+                ?.defaultType
+                ?.replace(kotlinType.arguments)
```
Comment (ting-yuan) [inline compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt:92]: Does this need to be done recursively, e.g., is `java.util.Container<java.util.Set>` assignable from `kotlin.collections.Set<kotlin.collections.Set>`?

**Review by ting-yuan — COMMENTED** [review]
1. I just recalled the discussion in #125, where whether java types and kotlin types should be assignable to each other were debated. Although I'm not too worried about the behavior change (which needs to be announced / emphasized in release notes though), all places that involve type checking need to be consistent. For example, overrides. How many places will need to be updated?

2. If I'm reading this right, does it mean that, before this PR, kotlin.collections.Set is assignable from java.util.Set but not the other way around?

File: compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt (hunk 1 above)
Comment (neetopia) [reply compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt:92]: I thought about this case when writing test, then realized it is impossible to do so, because we are only getting Java types via `getJavaClassByName`, from where we can only get a `KSType`, and because we only support build type argument with a type reference, therefore KSType can't be used to build a type argument. Which in turn, means that I can only try to get such test case in code, and while resolving types in source, all these types in the type arguments are already converted to kotlin types, therefore it is impossible to reproduce this in test case, nor in real practice.

**Comment by neetopia** [comment]
> 1. I just recalled the discussion in #125, where whether java types and kotlin types should be assignable to each other were debated. Although I'm not too worried about the behavior change (which needs to be announced / emphasized in release notes though), all places that involve type checking need to be consistent. For example, overrides. How many places will need to be updated?

I think the major issue here is that when getting a java class, we are not converting them into kotlin types, therefore left a door open for checking java types against kotlin types and breaks compiler subtype checking logic. Both compiler and KSP has been converting these Java types into Kotlin types and I think they are mostly working fine, we are only getting this issue in #890 because we allowed a non-converted type to be returned via `getJavaClassByName`

> 2. If I'm reading this right, does it mean that, before this PR, kotlin.collections.Set is assignable from java.util.Set but not the other way around?
Yes, actually this PR does not fix this case either, I will update PR to fix this.

**Comment by ting-yuan** [comment]
> > 1. I just recalled the discussion in [KSType assignability between java string and kotlin string returns false #125](https://github.com/google/ksp/issues/125), where whether java types and kotlin types should be assignable to each other were debated. Although I'm not too worried about the behavior change (which needs to be announced / emphasized in release notes though), all places that involve type checking need to be consistent. For example, overrides. How many places will need to be updated?
> 
> I think the major issue here is that when getting a java class, we are not converting them into kotlin types, therefore left a door open for checking java types against kotlin types and breaks compiler subtype checking logic. Both compiler and KSP has been converting these Java types into Kotlin types and I think they are mostly working fine, we are only getting this issue in #890 because we allowed a non-converted type to be returned via `getJavaClassByName`
> 

Allow me to rephrase: can you check places where `KSType` is used as a parameter and see whether they also need conversion or not?

File: compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt (hunk 1 above)
Comment (ting-yuan) [reply compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSTypeImpl.kt]: Except that we have `Resolver.createKSTypeReferenceFromKSType()` 😢

**Comment by neetopia** [comment]
> > > 1. I just recalled the discussion in [KSType assignability between java string and kotlin string returns false #125](https://github.com/google/ksp/issues/125), where whether java types and kotlin types should be assignable to each other were debated. Although I'm not too worried about the behavior change (which needs to be announced / emphasized in release notes though), all places that involve type checking need to be consistent. For example, overrides. How many places will need to be updated?
> > 
> > 
> > I think the major issue here is that when getting a java class, we are not converting them into kotlin types, therefore left a door open for checking java types against kotlin types and breaks compiler subtype checking logic. Both compiler and KSP has been converting these Java types into Kotlin types and I think they are mostly working fine, we are only getting this issue in #890 because we allowed a non-converted type to be returned via `getJavaClassByName`
> 
> Allow me to rephrase: can you check places where `KSType` is used as a parameter and see whether they also need conversion or not?


There are usages in asMemberOf, I will add a check there as well.

**Comment by neetopia** [comment]
Actually, because the implementation in `asMemberOf` is only checking super types already, not the type itself, same issue won't be happening for `asMemberOf`, although I do see a minor concern for `asMemberOf` not supporting the containing class to be itself, it does not seem to be a valid use case for `asMemberOf` anyway. I would fix it for `asMemberOf` if the subtype checking logic would include the type being checked itself.

**Review by ting-yuan — APPROVED** [review]
