### PR TITLE
Use correct psi implementation for finding type parameter declaration.

### LINKED ISSUE #1210: Resolved KSTypeParameter doesn't equal the source
For example,
```
interface Foo<T> {
    val t: T
}
```

I handle it below
```
val klassFoo = resolver.getClassDeclarationByName("Foo")!!
Log.w(klassFoo.typeParameters.first() == klassFoo.getDeclaredProperties().first().type.resolve().declaration)
```
The result is ```false```, which is unexpected because it's always ```true``` when that symbol is not ```KSTypeParameter```.

### PR DESCRIPTION
**Pull request by neetopia**
Fixes #1210.

### CODE REVIEW

File: compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt [hunk 1]
```diff
@@ -742,11 +742,12 @@ class ResolverImpl(
     fun findDeclaration(kotlinType: KotlinType): KSDeclaration {
         val descriptor = kotlinType.constructor.declarationDescriptor
         val psi = descriptor?.findPsi()
-        return if (psi != null && psi !is KtTypeParameter) {
```
Comment (neetopia) [inline compiler-plugin/src/main/kotlin/com/google/devtools/ksp/processing/impl/ResolverImpl.kt:745]: I can't recall why we filtered out type parameter here..

**Review by ting-yuan — APPROVED** [review]
