### PR TITLE
FIx findOverridee for properties, fixes #174

### LINKED ISSUE #174: Should KSPropertyDeclarationImpl.findOverridee use singleOrNull?
https://github.com/google/ksp/blob/638d9a19a9880056c8c95a5a2f5775045cb026ae/compiler-plugin/src/main/kotlin/com/google/devtools/ksp/symbol/impl/kotlin/KSPropertyDeclarationImpl.kt#L107

This now fails for me on an overridden val. The way this code is written now, looks like the last '?' in this part of the statement `.single { it.overriddenDescriptors.isEmpty() }?` is never going to happen, since `single` never returns null.

### PR DESCRIPTION
**Pull request by yigit**
This CL updates KSPropertyDecl.findOverridee to use the same infra
that is used by KSFunctionDeclaration.

Fixes: #174

### CODE REVIEW

**Review by neetopia — COMMENTED** [review]
The overriding for properties usually get complicated when it involves Java, can you add a test case where Java code is overriding a property declared in Kotlin code? See [this](https://github.com/google/ksp/blob/638d9a19a9880056c8c95a5a2f5775045cb026ae/compiler-plugin/testData/api/checkOverride.kt#L110) for example.

File: api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt [hunk 1]
```diff
@@ -58,8 +58,30 @@ interface KSPropertyDeclaration : KSDeclaration {
...
+     *   override val x:Int
+     *   override val y:Int
+     * }
+     * ```
+     * Calling `findOverridee` on `C.x` will return `B.x`.
+     * Calling `findOverridee` on `C.y` will return `A.y`.
+     *
+     * When there are multiple super classes / interfaces with the property, the closest declaration
+     * to the current containing declaration is selected. If they are in the same level, the
+     * property of the first specified interface (in source) will be returned.
```
Comment (neetopia) [inline api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: nit: `specified super class or interface` instead of `specified interface`

Comment (yigit) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: > The overriding for properties usually get complicated when it involves Java, can you add a test case where Java code is overriding a property declared in Kotlin code? See [this](https://github.com/google/ksp/blob/638d9a19a9880056c8c95a5a2f5775045cb026ae/compiler-plugin/testData/api/checkOverride.kt#L110) for example.

the findOverridee in the java implementation of property is not implemented (just returns null). I'm guessing that is because java fields do not override parents.

You mean there is a base kotlin class with `val x:T` and java overrides it with `getX():T`?
I'll give it a try but that makes me think, that would mean the `findOverridee` of `KSFunction` would need to return a `KSPropertyAccessor` that does not implement `KSFunction` :/. 
I'll see what happens there.

There was also some work discussed before where KSP right now does not properly resolve property accessors in java source code. If we do, then we should also implement findOverridee in KSPropertyDeclaration.

Comment (yigit) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: actually trying to reproduce that hits this issue:
https://github.com/google/ksp/issues/94

Comment (yigit) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: i'm actually able to workaround that issue by making KSJavaFileImpl use descriptors for the class instead of Java impls.
Java impls are causing lots of inconsistencies hence created this issue:
https://github.com/google/ksp/issues/177

Comment (mvdbos) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: Thanks for looking into this so fast. 

Question: is the merge of this PR blocked by the progress on #177? Or can this be merged already? It would help me a lot: until this is fixed, I need to maintain my fork. I use Kotlin only. :-)

Comment (yigit) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: @neetopia wdyt? I think this one is fine to merge as it should be an improvement over what we have (fixes kotlin properties, java is still broken).
#177 probably won't happen or if it happens it will take a long time.

Comment (neetopia) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: Sounds good, I'll merge this one.

**Review by neetopia — APPROVED** [review]

File: api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt (hunk 1 above)
Comment (mvdbos) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: Thanks for the merge. Is it possible to create a release that contains this? I am using KSP as a dependency.
If not, what is a likely date for a new release, given your release schedule?

Comment (neetopia) [reply api/src/main/kotlin/com/google/devtools/ksp/symbol/KSPropertyDeclaration.kt:82]: I'll do a release this Friday PST.
